apiVersion: "sco1237896.github.com/v1"
kind: "ConnectorDefinition"
metadata:
  name: "azure_storage_blob_changefeed_source_v1"
spec:
  definition:
    apiVersion: "camel.apache.org/v1"
    kind: "Pipe"
    metadata:
      annotations:
        sco1237896.github.com/catalog.group: "azure"
        sco1237896.github.com/catalog.id: "azure_storage_blob"
        sco1237896.github.com/connector.description: "Receive data from Azure Blob\
          \ storage change feed."
        sco1237896.github.com/connector.group: "azure"
        sco1237896.github.com/connector.id: "azure_storage_blob_changefeed_source_v1"
        sco1237896.github.com/connector.title: "Azure Blob Storage change feed source"
        sco1237896.github.com/connector.version: "v1"
        trait.camel.apache.org/container.request-cpu: "0.20"
        trait.camel.apache.org/container.request-memory: "128M"
        trait.camel.apache.org/deployment.progress-deadline-seconds: "30"
        trait.camel.apache.org/container.image: "quay.io/sco1237896/connector-azure-storage-blob:main-17140b59c01c7dd0a2d657dfcbf5c346ff4a6705"
    spec:
      errorHandler:
        log: {}
      sink:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-kafka-sink"
      source:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-azure-storage-blob-changefeed-source"
  resources:
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-azure-storage-blob-changefeed-source"
    spec:
      definition:
        title: "Azure Storage Blob Changefeed Source"
        description: "Consume events from an Azure Storage Blob change feed."
        required:
        - "period"
        - "accountName"
        - "accessKey"
        type: "object"
        properties:
          period:
            title: "Period between Polls"
            description: "The interval (in milliseconds) between fetches to the Azure\
              \ Storage change feed."
            type: "integer"
            default: 10000
          accountName:
            title: "Account Name"
            description: "The Azure Storage Blob account name."
            type: "string"
            x-descriptors:
            - "urn:camel:group:credentials"
          accessKey:
            title: "Access Key"
            description: "The Azure Storage Blob access Key."
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
          credentialType:
            title: "Credential Type"
            description: "Determines the credential strategy to adopt. Possible values\
              \ are SHARED_ACCOUNT_KEY, SHARED_KEY_CREDENTIAL and AZURE_IDENTITY"
            type: "string"
            default: "SHARED_ACCOUNT_KEY"
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-kafka-sink"
    spec:
      definition:
        title: "Managed Kafka Sink"
        description: |-
          Send data to Managed Kafka topics.

          Optionally, you can set the following properties in the header:

          - `key`: as message key

          - `partition-key`: as message partition key
        required:
        - "topic"
        - "bootstrapServers"
        type: "object"
        properties:
          topic:
            title: "Topic Name"
            description: "The name of the Kafka Topic to use."
            type: "string"
          bootstrapServers:
            title: "Bootstrap Servers"
            description: "Comma separated list of Kafka Broker URLs"
            type: "string"
          securityProtocol:
            title: "Security Protocol"
            description: "Protocol used to communicate with brokers. SASL_PLAINTEXT,\
              \ PLAINTEXT, SASL_SSL and SSL are supported"
            type: "string"
          saslMechanism:
            title: "SASL Mechanism"
            description: "The Simple Authentication and Security Layer (SASL) Mechanism\
              \ used."
            type: "string"
          user:
            title: "Username"
            description: "Username to authenticate to Kafka"
            type: "string"
            x-descriptors:
            - "urn:camel:group:credentials"
          password:
            title: "Password"
            description: "Password to authenticate to kafka"
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
