apiVersion: "sco1237896.github.com/v1"
kind: "ConnectorDefinition"
metadata:
  name: "azure_eventhubs_sink_v1"
spec:
  definition:
    apiVersion: "camel.apache.org/v1"
    kind: "Pipe"
    metadata:
      annotations:
        sco1237896.github.com/catalog.group: "azure"
        sco1237896.github.com/catalog.id: "azure_eventhubs"
        sco1237896.github.com/connector.description: "Send data to Azure Event Hubs."
        sco1237896.github.com/connector.group: "azure"
        sco1237896.github.com/connector.id: "azure_eventhubs_sink_v1"
        sco1237896.github.com/connector.title: "Azure Event Hubs sink"
        sco1237896.github.com/connector.version: "v1"
        trait.camel.apache.org/container.request-cpu: "0.20"
        trait.camel.apache.org/container.request-memory: "128M"
        trait.camel.apache.org/deployment.progress-deadline-seconds: "30"
        trait.camel.apache.org/container.image: "quay.io/sco1237896/connector-azure-eventhubs:main-17140b59c01c7dd0a2d657dfcbf5c346ff4a6705"
    spec:
      errorHandler:
        log: {}
      sink:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-azure-eventhubs-sink"
      source:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-kafka-source"
  resources:
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-kafka-source"
    spec:
      definition:
        title: "Managed Kafka Source"
        description: "Receive data from Managed Kafka topics."
        required:
        - "topic"
        - "bootstrapServers"
        type: "object"
        properties:
          topic:
            title: "Topic Names"
            description: "A comma-separated list of Kafka topic names."
            type: "string"
          bootstrapServers:
            title: "Bootstrap Servers"
            description: "Comma separated list of Kafka Broker URLs"
            type: "string"
          securityProtocol:
            title: "Security Protocol"
            description: "Protocol used to communicate with brokers. SASL_PLAINTEXT,\
              \ PLAINTEXT, SASL_SSL and SSL are supported"
            type: "string"
          saslMechanism:
            title: "SASL Mechanism"
            description: "The Simple Authentication and Security Layer (SASL) Mechanism\
              \ used."
            type: "string"
          user:
            title: "Username"
            description: "Username to authenticate to Kafka"
            type: "string"
            x-descriptors:
            - "urn:camel:group:credentials"
          password:
            title: "Password"
            description: "Password to authenticate to kafka"
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-azure-eventhubs-sink"
    spec:
      definition:
        title: "Azure Eventhubs Sink"
        description: |-
          Send Events to Azure Eventhubs.

          The Kamelet is able to understand the following headers to be set:

          - `partition` / `ce-partition`: as the time to live of the message in the queue.

          If the header won't be set then the partition will be assigned by Eventhubs
        required:
        - "namespaceName"
        - "eventhubName"
        - "sharedAccessName"
        - "sharedAccessKey"
        type: "object"
        properties:
          namespaceName:
            title: "Eventhubs Namespace"
            description: "The eventhubs namespace"
            type: "string"
          eventhubName:
            title: "Eventhubs Name"
            description: "The eventhub name"
            type: "string"
          sharedAccessName:
            title: "Share Access Name"
            description: "EventHubs SAS key name"
            type: "string"
            x-descriptors:
            - "urn:camel:group:credentials"
          sharedAccessKey:
            title: "Share Access Key"
            description: "The key for EventHubs SAS key name"
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
