apiVersion: "sco1237896.github.com/v1"
kind: "ConnectorDefinition"
metadata:
  name: "azure_storage_queue_source_v1"
spec:
  definition:
    apiVersion: "camel.apache.org/v1"
    kind: "Pipe"
    metadata:
      annotations:
        sco1237896.github.com/catalog.group: "azure"
        sco1237896.github.com/catalog.id: "azure_storage_queue"
        sco1237896.github.com/connector.description: "Receive data from Azure Queue\
          \ Storage."
        sco1237896.github.com/connector.group: "azure"
        sco1237896.github.com/connector.id: "azure_storage_queue_source_v1"
        sco1237896.github.com/connector.title: "Azure Queue Storage source"
        sco1237896.github.com/connector.version: "v1"
        trait.camel.apache.org/container.request-cpu: "0.20"
        trait.camel.apache.org/container.request-memory: "128M"
        trait.camel.apache.org/deployment.progress-deadline-seconds: "30"
        trait.camel.apache.org/container.image: "quay.io/sco1237896/connector-azure-storage-queue:main-b0bc19971c883b500f8fbf96545c4dbefdaf8e9a"
    spec:
      errorHandler:
        log: {}
      sink:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-kafka-sink"
      source:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-azure-storage-queue-source"
  resources:
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-azure-storage-queue-source"
    spec:
      definition:
        title: "Azure Storage Queue Source"
        description: "Receive events from Azure Storage queues."
        required:
        - "accountName"
        - "queueName"
        - "accessKey"
        type: "object"
        properties:
          accountName:
            title: "Account Name"
            description: "The Azure Storage Queue account name."
            type: "string"
            x-descriptors:
            - "urn:camel:group:credentials"
          queueName:
            title: "Queue Name"
            description: "The Azure Storage Queue container name."
            type: "string"
          accessKey:
            title: "Access Key"
            description: "The Azure Storage Queue access key."
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
          maxMessages:
            title: "Maximum Messages"
            description: "The maximum number of messages to get. You can specify a\
              \ value between 1 and 32. The default is 1 (one message). If there are\
              \ fewer than the maximum number of messages in the queue, then all the\
              \ messages are returned."
            type: "integer"
            default: 1
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-kafka-sink"
    spec:
      definition:
        title: "Managed Kafka Sink"
        description: |-
          Send data to Managed Kafka topics.

          Optionally, you can set the following properties in the header:

          - `key`: as message key

          - `partition-key`: as message partition key
        required:
        - "topic"
        - "bootstrapServers"
        type: "object"
        properties:
          topic:
            title: "Topic Name"
            description: "The name of the Kafka Topic to use."
            type: "string"
          bootstrapServers:
            title: "Bootstrap Servers"
            description: "Comma separated list of Kafka Broker URLs"
            type: "string"
          securityProtocol:
            title: "Security Protocol"
            description: "Protocol used to communicate with brokers. SASL_PLAINTEXT,\
              \ PLAINTEXT, SASL_SSL and SSL are supported"
            type: "string"
          saslMechanism:
            title: "SASL Mechanism"
            description: "The Simple Authentication and Security Layer (SASL) Mechanism\
              \ used."
            type: "string"
          user:
            title: "Username"
            description: "Username to authenticate to Kafka"
            type: "string"
            x-descriptors:
            - "urn:camel:group:credentials"
          password:
            title: "Password"
            description: "Password to authenticate to kafka"
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
