apiVersion: "sco1237896.github.com/v1"
kind: "ConnectorDefinition"
metadata:
  name: "azure_functions_sink_v1"
spec:
  definition:
    apiVersion: "camel.apache.org/v1"
    kind: "Pipe"
    metadata:
      annotations:
        sco1237896.github.com/catalog.group: "azure"
        sco1237896.github.com/catalog.id: "azure_functions"
        sco1237896.github.com/connector.description: "Send data to Functions."
        sco1237896.github.com/connector.group: "azure"
        sco1237896.github.com/connector.id: "azure_functions_sink_v1"
        sco1237896.github.com/connector.title: "Azure Functions sink"
        sco1237896.github.com/connector.version: "v1"
        trait.camel.apache.org/container.request-cpu: "0.20"
        trait.camel.apache.org/container.request-memory: "128M"
        trait.camel.apache.org/deployment.progress-deadline-seconds: "30"
        trait.camel.apache.org/container.image: "quay.io/sco1237896/connector-azure-functions:main-b0bc19971c883b500f8fbf96545c4dbefdaf8e9a"
    spec:
      errorHandler:
        log: {}
      sink:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-azure-functions-sink"
      source:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-kafka-source"
  resources:
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-kafka-source"
    spec:
      definition:
        title: "Managed Kafka Source"
        description: "Receive data from Managed Kafka topics."
        required:
        - "topic"
        - "bootstrapServers"
        type: "object"
        properties:
          topic:
            title: "Topic Names"
            description: "A comma-separated list of Kafka topic names."
            type: "string"
          bootstrapServers:
            title: "Bootstrap Servers"
            description: "Comma separated list of Kafka Broker URLs"
            type: "string"
          securityProtocol:
            title: "Security Protocol"
            description: "Protocol used to communicate with brokers. SASL_PLAINTEXT,\
              \ PLAINTEXT, SASL_SSL and SSL are supported"
            type: "string"
          saslMechanism:
            title: "SASL Mechanism"
            description: "The Simple Authentication and Security Layer (SASL) Mechanism\
              \ used."
            type: "string"
          user:
            title: "Username"
            description: "Username to authenticate to Kafka"
            type: "string"
            x-descriptors:
            - "urn:camel:group:credentials"
          password:
            title: "Password"
            description: "Password to authenticate to kafka"
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-azure-functions-sink"
    spec:
      definition:
        title: "Azure Function Sink"
        description: "Forward data to an Azure Function."
        required:
        - "url"
        type: "object"
        properties:
          url:
            title: "URL"
            description: "The Azure Functions URL you want to send the data to."
            type: "string"
            example: "https://azure-function-demo-12234.azurewebsites.net/api/httpexample"
            pattern: "^(https)://.*"
          method:
            title: "Method"
            description: "The HTTP method to use."
            type: "string"
            default: "POST"
            enum:
            - "GET"
            - "POST"
            - "PUT"
            - "DELETE"
            - "HEAD"
            - "OPTIONS"
            - "TRACE"
            - "PATCH"
          key:
            title: "Key"
            description: "A function-specific API key is required, if the authLevel\
              \ of the function is FUNCTION or master key if the authLevel is ADMIN."
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
