apiVersion: "sco1237896.github.com/v1"
kind: "ConnectorDefinition"
metadata:
  name: "azure_eventhubs_source_v1"
spec:
  definition:
    apiVersion: "camel.apache.org/v1"
    kind: "Pipe"
    metadata:
      annotations:
        sco1237896.github.com/catalog.group: "azure"
        sco1237896.github.com/catalog.id: "azure_eventhubs"
        sco1237896.github.com/connector.description: "Receive data from Azure Event\
          \ Hubs.."
        sco1237896.github.com/connector.group: "azure"
        sco1237896.github.com/connector.id: "azure_eventhubs_source_v1"
        sco1237896.github.com/connector.title: "Azure Event Hubs source"
        sco1237896.github.com/connector.version: "v1"
        trait.camel.apache.org/container.request-cpu: "0.20"
        trait.camel.apache.org/container.request-memory: "128M"
        trait.camel.apache.org/deployment.progress-deadline-seconds: "30"
        trait.camel.apache.org/container.image: "quay.io/sco1237896/connector-azure-eventhubs:main-b0bc19971c883b500f8fbf96545c4dbefdaf8e9a"
    spec:
      errorHandler:
        log: {}
      sink:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-kafka-sink"
      source:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-azure-eventhubs-source"
  resources:
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-azure-eventhubs-source"
    spec:
      definition:
        title: "Azure Eventhubs Source"
        description: "Receive events from Azure Event Hubs."
        required:
        - "namespaceName"
        - "eventhubName"
        - "sharedAccessName"
        - "sharedAccessKey"
        - "blobAccountName"
        - "blobAccessKey"
        - "blobContainerName"
        type: "object"
        properties:
          namespaceName:
            title: "Eventhubs Namespace"
            description: "The Event Hubs namespace."
            type: "string"
          eventhubName:
            title: "Eventhubs Name"
            description: "The Event Hub name."
            type: "string"
          sharedAccessName:
            title: "Share Access Name"
            description: "The Event Hubs SAS key name."
            type: "string"
            x-descriptors:
            - "urn:camel:group:credentials"
          sharedAccessKey:
            title: "Share Access Key"
            description: "The key for the Event Hubs SAS key name."
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
          blobAccountName:
            title: "Azure Storage Blob Account Name"
            description: "The name of the Storage Blob account."
            type: "string"
          blobContainerName:
            title: "Azure Storage Blob Container Name"
            description: "The name of the Storage Blob container."
            type: "string"
          blobAccessKey:
            title: "Azure Storage Blob Access Key"
            description: "The key for the Azure Storage Blob service that is associated\
              \ with the Storage Blob account name."
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
      types:
        out:
          mediaType: "application/octet-stream"
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-kafka-sink"
    spec:
      definition:
        title: "Managed Kafka Sink"
        description: |-
          Send data to Managed Kafka topics.

          Optionally, you can set the following properties in the header:

          - `key`: as message key

          - `partition-key`: as message partition key
        required:
        - "topic"
        - "bootstrapServers"
        type: "object"
        properties:
          topic:
            title: "Topic Name"
            description: "The name of the Kafka Topic to use."
            type: "string"
          bootstrapServers:
            title: "Bootstrap Servers"
            description: "Comma separated list of Kafka Broker URLs"
            type: "string"
          securityProtocol:
            title: "Security Protocol"
            description: "Protocol used to communicate with brokers. SASL_PLAINTEXT,\
              \ PLAINTEXT, SASL_SSL and SSL are supported"
            type: "string"
          saslMechanism:
            title: "SASL Mechanism"
            description: "The Simple Authentication and Security Layer (SASL) Mechanism\
              \ used."
            type: "string"
          user:
            title: "Username"
            description: "Username to authenticate to Kafka"
            type: "string"
            x-descriptors:
            - "urn:camel:group:credentials"
          password:
            title: "Password"
            description: "Password to authenticate to kafka"
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
