apiVersion: "sco1237896.github.com/v1"
kind: "ConnectorDefinition"
metadata:
  name: "google_pubsub_source_v1"
spec:
  definition:
    apiVersion: "camel.apache.org/v1"
    kind: "Pipe"
    metadata:
      annotations:
        sco1237896.github.com/catalog.group: "gcp"
        sco1237896.github.com/catalog.id: "google_pubsub"
        sco1237896.github.com/connector.description: "Receive data from Google Cloud\
          \ Pub/Sub."
        sco1237896.github.com/connector.group: "gcp"
        sco1237896.github.com/connector.id: "google_pubsub_source_v1"
        sco1237896.github.com/connector.title: "Google Cloud Pub/Sub source"
        sco1237896.github.com/connector.version: "v1"
        trait.camel.apache.org/container.request-cpu: "0.20"
        trait.camel.apache.org/container.request-memory: "128M"
        trait.camel.apache.org/deployment.progress-deadline-seconds: "30"
        trait.camel.apache.org/container.image: "quay.io/sco1237896/connector-google-pubsub:main-17140b59c01c7dd0a2d657dfcbf5c346ff4a6705"
    spec:
      errorHandler:
        log: {}
      sink:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-kafka-sink"
      source:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-google-pubsub-source"
  resources:
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-google-pubsub-source"
    spec:
      definition:
        title: "Google Pubsub Source"
        description: "Consume messages from Google Cloud Pub/Sub."
        required:
        - "projectId"
        - "subscriptionName"
        - "serviceAccountKey"
        type: "object"
        properties:
          projectId:
            title: "Project Id"
            description: "The Google Cloud Pub/Sub Project ID."
            type: "string"
          subscriptionName:
            title: "Subscription Name"
            description: "The subscription name."
            type: "string"
          serviceAccountKey:
            title: "Service Account Key"
            description: "The service account key to use as credentials for the Pub/Sub\
              \ publisher/subscriber. You must encode this value in base64."
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
          synchronousPull:
            title: "Synchronous Pull"
            description: "Specifies to synchronously pull batches of messages."
            type: "boolean"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:checkbox"
            default: false
          maxMessagesPerPoll:
            title: "Max Messages Per Poll"
            description: "The maximum number of messages to receive from the server\
              \ in a single API call."
            type: "integer"
            default: 1
          concurrentConsumers:
            title: "Concurrent Consumers"
            description: "The number of parallel streams to consume from the subscription."
            type: "integer"
            default: 1
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-kafka-sink"
    spec:
      definition:
        title: "Managed Kafka Sink"
        description: |-
          Send data to Managed Kafka topics.

          Optionally, you can set the following properties in the header:

          - `key`: as message key

          - `partition-key`: as message partition key
        required:
        - "topic"
        - "bootstrapServers"
        type: "object"
        properties:
          topic:
            title: "Topic Name"
            description: "The name of the Kafka Topic to use."
            type: "string"
          bootstrapServers:
            title: "Bootstrap Servers"
            description: "Comma separated list of Kafka Broker URLs"
            type: "string"
          securityProtocol:
            title: "Security Protocol"
            description: "Protocol used to communicate with brokers. SASL_PLAINTEXT,\
              \ PLAINTEXT, SASL_SSL and SSL are supported"
            type: "string"
          saslMechanism:
            title: "SASL Mechanism"
            description: "The Simple Authentication and Security Layer (SASL) Mechanism\
              \ used."
            type: "string"
          user:
            title: "Username"
            description: "Username to authenticate to Kafka"
            type: "string"
            x-descriptors:
            - "urn:camel:group:credentials"
          password:
            title: "Password"
            description: "Password to authenticate to kafka"
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
