apiVersion: "sco1237896.github.com/v1"
kind: "ConnectorDefinition"
metadata:
  name: "google_bigquery_sink_v1"
spec:
  definition:
    apiVersion: "camel.apache.org/v1"
    kind: "Pipe"
    metadata:
      annotations:
        sco1237896.github.com/catalog.group: "gcp"
        sco1237896.github.com/catalog.id: "google_bigquery"
        sco1237896.github.com/connector.description: "Send data to a Google Big Query\
          \ table."
        sco1237896.github.com/connector.group: "gcp"
        sco1237896.github.com/connector.id: "google_bigquery_sink_v1"
        sco1237896.github.com/connector.title: "Google BigQuery sink"
        sco1237896.github.com/connector.version: "v1"
        trait.camel.apache.org/container.request-cpu: "0.20"
        trait.camel.apache.org/container.request-memory: "128M"
        trait.camel.apache.org/deployment.progress-deadline-seconds: "30"
        trait.camel.apache.org/container.image: "quay.io/sco1237896/connector-google-bigquery:main-17140b59c01c7dd0a2d657dfcbf5c346ff4a6705"
    spec:
      errorHandler:
        log: {}
      sink:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-google-bigquery-sink"
      source:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-kafka-source"
  resources:
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-kafka-source"
    spec:
      definition:
        title: "Managed Kafka Source"
        description: "Receive data from Managed Kafka topics."
        required:
        - "topic"
        - "bootstrapServers"
        type: "object"
        properties:
          topic:
            title: "Topic Names"
            description: "A comma-separated list of Kafka topic names."
            type: "string"
          bootstrapServers:
            title: "Bootstrap Servers"
            description: "Comma separated list of Kafka Broker URLs"
            type: "string"
          securityProtocol:
            title: "Security Protocol"
            description: "Protocol used to communicate with brokers. SASL_PLAINTEXT,\
              \ PLAINTEXT, SASL_SSL and SSL are supported"
            type: "string"
          saslMechanism:
            title: "SASL Mechanism"
            description: "The Simple Authentication and Security Layer (SASL) Mechanism\
              \ used."
            type: "string"
          user:
            title: "Username"
            description: "Username to authenticate to Kafka"
            type: "string"
            x-descriptors:
            - "urn:camel:group:credentials"
          password:
            title: "Password"
            description: "Password to authenticate to kafka"
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-google-bigquery-sink"
    spec:
      definition:
        title: "Google Big Query Sink"
        description: |-
          Send data to a Google Big Query table.

          The data must be JSON format to represent an object or an array of objects.
        required:
        - "projectId"
        - "dataset"
        - "table"
        - "serviceAccountKey"
        type: "object"
        properties:
          projectId:
            title: "Google Cloud Project Id"
            description: "The Google Cloud Project ID."
            type: "string"
          dataset:
            title: "Big Query Dataset Id"
            description: "The Big Query Dataset ID."
            type: "string"
          table:
            title: "Big Query Table Id"
            description: "The Big Query Table ID."
            type: "string"
          serviceAccountKey:
            title: "Service Account Key"
            description: "The service account key to use as credentials for the BigQuery\
              \ Service. You must encode this value in base64."
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
      types:
        in:
          mediaType: "application/json"
