apiVersion: "sco1237896.github.com/v1"
kind: "ConnectorDefinition"
metadata:
  name: "slack_sink_v1"
spec:
  definition:
    apiVersion: "camel.apache.org/v1"
    kind: "Pipe"
    metadata:
      annotations:
        sco1237896.github.com/catalog.group: "social"
        sco1237896.github.com/catalog.id: "slack"
        sco1237896.github.com/connector.description: "Send messages to a Slack channel."
        sco1237896.github.com/connector.group: "social"
        sco1237896.github.com/connector.id: "slack_sink_v1"
        sco1237896.github.com/connector.title: "Slack sink"
        sco1237896.github.com/connector.version: "v1"
        trait.camel.apache.org/container.request-cpu: "0.20"
        trait.camel.apache.org/container.request-memory: "128M"
        trait.camel.apache.org/deployment.progress-deadline-seconds: "30"
        trait.camel.apache.org/container.image: "quay.io/sco1237896/connector-slack:main-17140b59c01c7dd0a2d657dfcbf5c346ff4a6705"
    spec:
      errorHandler:
        log: {}
      sink:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-slack-sink"
      source:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-kafka-source"
  resources:
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-kafka-source"
    spec:
      definition:
        title: "Managed Kafka Source"
        description: "Receive data from Managed Kafka topics."
        required:
        - "topic"
        - "bootstrapServers"
        type: "object"
        properties:
          topic:
            title: "Topic Names"
            description: "A comma-separated list of Kafka topic names."
            type: "string"
          bootstrapServers:
            title: "Bootstrap Servers"
            description: "Comma separated list of Kafka Broker URLs"
            type: "string"
          securityProtocol:
            title: "Security Protocol"
            description: "Protocol used to communicate with brokers. SASL_PLAINTEXT,\
              \ PLAINTEXT, SASL_SSL and SSL are supported"
            type: "string"
          saslMechanism:
            title: "SASL Mechanism"
            description: "The Simple Authentication and Security Layer (SASL) Mechanism\
              \ used."
            type: "string"
          user:
            title: "Username"
            description: "Username to authenticate to Kafka"
            type: "string"
            x-descriptors:
            - "urn:camel:group:credentials"
          password:
            title: "Password"
            description: "Password to authenticate to kafka"
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-slack-sink"
    spec:
      definition:
        title: "Slack Sink"
        description: "Send messages to a Slack channel."
        required:
        - "channel"
        - "webhookUrl"
        type: "object"
        properties:
          channel:
            title: "Channel"
            description: "The Slack channel to send messages to."
            type: "string"
            example: "#myroom"
          webhookUrl:
            title: "Webhook URL"
            description: "The webhook URL used by the Slack channel to handle incoming\
              \ messages."
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
          iconEmoji:
            title: "Icon Emoji"
            description: "Use a Slack emoji as an avatar."
            type: "string"
          iconUrl:
            title: "Icon URL"
            description: "The avatar to use when sending a message to a channel or\
              \ user."
            type: "string"
          username:
            title: "Username"
            description: "The username for the bot when it sends messages to a channel\
              \ or user."
            type: "string"
      types:
        out:
          mediaType: "application/json"
