apiVersion: "sco1237896.github.com/v1"
kind: "ConnectorDefinition"
metadata:
  name: "cassandra_sink_v1"
spec:
  definition:
    apiVersion: "camel.apache.org/v1"
    kind: "Pipe"
    metadata:
      annotations:
        sco1237896.github.com/catalog.group: "nosql"
        sco1237896.github.com/catalog.id: "cassandra"
        sco1237896.github.com/connector.description: "Send data to an Apache Cassandra\
          \ cluster."
        sco1237896.github.com/connector.group: "nosql"
        sco1237896.github.com/connector.id: "cassandra_sink_v1"
        sco1237896.github.com/connector.title: "Apache Cassandra sink"
        sco1237896.github.com/connector.version: "v1"
        trait.camel.apache.org/container.request-cpu: "0.20"
        trait.camel.apache.org/container.request-memory: "128M"
        trait.camel.apache.org/deployment.progress-deadline-seconds: "30"
        trait.camel.apache.org/container.image: "quay.io/sco1237896/connector-cassandra:main-b0bc19971c883b500f8fbf96545c4dbefdaf8e9a"
    spec:
      errorHandler:
        log: {}
      sink:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-cassandra-sink"
      source:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-kafka-source"
  resources:
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-kafka-source"
    spec:
      definition:
        title: "Managed Kafka Source"
        description: "Receive data from Managed Kafka topics."
        required:
        - "topic"
        - "bootstrapServers"
        type: "object"
        properties:
          topic:
            title: "Topic Names"
            description: "A comma-separated list of Kafka topic names."
            type: "string"
          bootstrapServers:
            title: "Bootstrap Servers"
            description: "Comma separated list of Kafka Broker URLs"
            type: "string"
          securityProtocol:
            title: "Security Protocol"
            description: "Protocol used to communicate with brokers. SASL_PLAINTEXT,\
              \ PLAINTEXT, SASL_SSL and SSL are supported"
            type: "string"
          saslMechanism:
            title: "SASL Mechanism"
            description: "The Simple Authentication and Security Layer (SASL) Mechanism\
              \ used."
            type: "string"
          user:
            title: "Username"
            description: "Username to authenticate to Kafka"
            type: "string"
            x-descriptors:
            - "urn:camel:group:credentials"
          password:
            title: "Password"
            description: "Password to authenticate to kafka"
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-cassandra-sink"
    spec:
      definition:
        title: "Cassandra Sink"
        description: |-
          Send data to an Apache Cassandra cluster.

          This Kamelet expects JSON Array formatted data. The content of the JSON Array is used as input for the CQL Prepared Statement set in the query parameter.
        required:
        - "connectionHost"
        - "connectionPort"
        - "keyspace"
        - "query"
        type: "object"
        properties:
          connectionHost:
            title: "Connection Host"
            description: "The hostname(s) for the Cassandra server(s). Use a comma\
              \ to separate multiple hostnames."
            type: "string"
            example: "localhost"
          connectionPort:
            title: "Connection Port"
            description: "The port number(s) of the cassandra server(s). Use a comma\
              \ to separate multiple port numbers."
            type: "string"
            example: 9042
          keyspace:
            title: "Keyspace"
            description: "The keyspace to use."
            type: "string"
            example: "customers"
          username:
            title: "Username"
            description: "The username for accessing a secured Cassandra cluster."
            type: "string"
            x-descriptors:
            - "urn:camel:group:credentials"
          password:
            title: "Password"
            description: "The password for accessing a secured Cassandra cluster."
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
          consistencyLevel:
            title: "Consistency Level"
            description: "The consistency level to use."
            type: "string"
            default: "ANY"
            enum:
            - "ANY"
            - "ONE"
            - "TWO"
            - "THREE"
            - "QUORUM"
            - "ALL"
            - "LOCAL_QUORUM"
            - "EACH_QUORUM"
            - "LOCAL_ONE"
          prepareStatements:
            title: "Prepare Statements"
            description: "If true, specifies to use PreparedStatements as the query.\
              \ If false, specifies to use regular Statements as the query."
            type: "boolean"
            default: true
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:checkbox"
          query:
            title: "Query"
            description: "The query to execute against the Cassandra cluster table."
            type: "string"
      types:
        in:
          mediaType: "application/json"
