apiVersion: "sco1237896.github.com/v1"
kind: "ConnectorDefinition"
metadata:
  name: "mongodb_sink_v1"
spec:
  definition:
    apiVersion: "camel.apache.org/v1"
    kind: "Pipe"
    metadata:
      annotations:
        sco1237896.github.com/catalog.group: "nosql"
        sco1237896.github.com/catalog.id: "mongodb"
        sco1237896.github.com/connector.description: "Send data to MongoDB."
        sco1237896.github.com/connector.group: "nosql"
        sco1237896.github.com/connector.id: "mongodb_sink_v1"
        sco1237896.github.com/connector.title: "MongoDB sink"
        sco1237896.github.com/connector.version: "v1"
        trait.camel.apache.org/container.request-cpu: "0.20"
        trait.camel.apache.org/container.request-memory: "128M"
        trait.camel.apache.org/deployment.progress-deadline-seconds: "30"
        trait.camel.apache.org/container.image: "quay.io/sco1237896/connector-mongodb:main-17140b59c01c7dd0a2d657dfcbf5c346ff4a6705"
    spec:
      errorHandler:
        log: {}
      sink:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-mongodb-sink"
      source:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-kafka-source"
  resources:
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-kafka-source"
    spec:
      definition:
        title: "Managed Kafka Source"
        description: "Receive data from Managed Kafka topics."
        required:
        - "topic"
        - "bootstrapServers"
        type: "object"
        properties:
          topic:
            title: "Topic Names"
            description: "A comma-separated list of Kafka topic names."
            type: "string"
          bootstrapServers:
            title: "Bootstrap Servers"
            description: "Comma separated list of Kafka Broker URLs"
            type: "string"
          securityProtocol:
            title: "Security Protocol"
            description: "Protocol used to communicate with brokers. SASL_PLAINTEXT,\
              \ PLAINTEXT, SASL_SSL and SSL are supported"
            type: "string"
          saslMechanism:
            title: "SASL Mechanism"
            description: "The Simple Authentication and Security Layer (SASL) Mechanism\
              \ used."
            type: "string"
          user:
            title: "Username"
            description: "Username to authenticate to Kafka"
            type: "string"
            x-descriptors:
            - "urn:camel:group:credentials"
          password:
            title: "Password"
            description: "Password to authenticate to kafka"
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-mongodb-sink"
    spec:
      definition:
        title: "MongoDB Sink"
        required:
        - "hosts"
        - "collection"
        - "database"
        type: "object"
        properties:
          hosts:
            title: "MongoDB Hosts"
            description: "Comma separated list of MongoDB Host Addresses in host:port\
              \ format."
            type: "string"
          collection:
            title: "MongoDB Collection"
            description: "Sets the name of the MongoDB collection to bind to this\
              \ endpoint."
            type: "string"
          password:
            title: "MongoDB Password"
            description: "User password for accessing MongoDB."
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
          username:
            title: "MongoDB Username"
            description: "Username for accessing MongoDB."
            type: "string"
            x-descriptors:
            - "urn:camel:group:credentials"
          ssl:
            title: "Enable ssl for mongodb connection"
            description: "whether to enable ssl connection to mongodb"
            type: "boolean"
            default: true
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:checkbox"
          sslValidationEnabled:
            title: "Enables ssl certificates validation and host name checks."
            description: "IMPORTANT this should be disabled only in test environment\
              \ since can pose security issues."
            type: "boolean"
            default: true
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:checkbox"
          database:
            title: "MongoDB Database"
            description: "Sets the name of the MongoDB database to target."
            type: "string"
          writeConcern:
            title: "Write Concern"
            description: "Configure the level of acknowledgment requested from MongoDB\
              \ for write operations, possible values are ACKNOWLEDGED, W1, W2, W3,\
              \ UNACKNOWLEDGED, JOURNALED, MAJORITY."
            type: "string"
          createCollection:
            title: "Collection"
            description: "Create collection during initialisation if it doesn't exist."
            type: "boolean"
            default: false
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:checkbox"
      types:
        in:
          mediaType: "application/json"
