apiVersion: "sco1237896.github.com/v1"
kind: "ConnectorDefinition"
metadata:
  name: "minio_sink_v1"
spec:
  definition:
    apiVersion: "camel.apache.org/v1"
    kind: "Pipe"
    metadata:
      annotations:
        sco1237896.github.com/catalog.group: "storage"
        sco1237896.github.com/catalog.id: "minio"
        sco1237896.github.com/connector.description: "Send data to MinIO."
        sco1237896.github.com/connector.group: "storage"
        sco1237896.github.com/connector.id: "minio_sink_v1"
        sco1237896.github.com/connector.title: "MinIO sink"
        sco1237896.github.com/connector.version: "v1"
        trait.camel.apache.org/container.request-cpu: "0.20"
        trait.camel.apache.org/container.request-memory: "128M"
        trait.camel.apache.org/deployment.progress-deadline-seconds: "30"
        trait.camel.apache.org/container.image: "quay.io/sco1237896/connector-minio:main-b0bc19971c883b500f8fbf96545c4dbefdaf8e9a"
    spec:
      errorHandler:
        log: {}
      sink:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-minio-sink"
      source:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-kafka-source"
  resources:
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-kafka-source"
    spec:
      definition:
        title: "Managed Kafka Source"
        description: "Receive data from Managed Kafka topics."
        required:
        - "topic"
        - "bootstrapServers"
        type: "object"
        properties:
          topic:
            title: "Topic Names"
            description: "A comma-separated list of Kafka topic names."
            type: "string"
          bootstrapServers:
            title: "Bootstrap Servers"
            description: "Comma separated list of Kafka Broker URLs"
            type: "string"
          securityProtocol:
            title: "Security Protocol"
            description: "Protocol used to communicate with brokers. SASL_PLAINTEXT,\
              \ PLAINTEXT, SASL_SSL and SSL are supported"
            type: "string"
          saslMechanism:
            title: "SASL Mechanism"
            description: "The Simple Authentication and Security Layer (SASL) Mechanism\
              \ used."
            type: "string"
          user:
            title: "Username"
            description: "Username to authenticate to Kafka"
            type: "string"
            x-descriptors:
            - "urn:camel:group:credentials"
          password:
            title: "Password"
            description: "Password to authenticate to kafka"
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-minio-sink"
    spec:
      definition:
        title: "Minio Sink"
        description: |-
          Upload data to MinIO.

          In the header, you can set the `file` / `ce-file` property to specify the filename to upload.

          If you do not set the property in the header, the Kamelet uses the exchange ID for the filename.
        required:
        - "bucketName"
        - "accessKey"
        - "secretKey"
        - "endpoint"
        type: "object"
        properties:
          bucketName:
            title: "Bucket Name"
            description: "The Minio Bucket name."
            type: "string"
          accessKey:
            title: "Access Key"
            description: "The access key obtained from MinIO."
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
          secretKey:
            title: "Secret Key"
            description: "The secret key obtained from MinIO."
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
          endpoint:
            title: "Endpoint"
            description: "The MinIO Endpoint. You can specify an URL, domain name,\
              \ IPv4 address, or IPv6 address."
            type: "string"
            example: "http://localhost:9000"
          autoCreateBucket:
            title: "Autocreate Bucket"
            description: "Specify to automatically create the MinIO bucket."
            type: "boolean"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:checkbox"
            default: false
