apiVersion: "sco1237896.github.com/v1"
kind: "ConnectorDefinition"
metadata:
  name: "jms_apache_artemis_source_v1"
spec:
  definition:
    apiVersion: "camel.apache.org/v1"
    kind: "Pipe"
    metadata:
      annotations:
        sco1237896.github.com/catalog.group: "messaging"
        sco1237896.github.com/catalog.id: "jms_apache_artemis"
        sco1237896.github.com/connector.description: "Receive data from an Apache\
          \ Artemis message broker by using JMS."
        sco1237896.github.com/connector.group: "messaging"
        sco1237896.github.com/connector.id: "jms_apache_artemis_source_v1"
        sco1237896.github.com/connector.title: "JMS Apache Artemis source"
        sco1237896.github.com/connector.version: "v1"
        trait.camel.apache.org/container.request-cpu: "0.20"
        trait.camel.apache.org/container.request-memory: "128M"
        trait.camel.apache.org/deployment.progress-deadline-seconds: "30"
        trait.camel.apache.org/container.image: "quay.io/sco1237896/connector-jms-apache-artemis:main-b0bc19971c883b500f8fbf96545c4dbefdaf8e9a"
    spec:
      errorHandler:
        log: {}
      sink:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-kafka-sink"
      source:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-jms-apache-artemis-source"
  resources:
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-jms-apache-artemis-source"
    spec:
      definition:
        title: "JMS - Apache Artemis Kamelet Source"
        description: "Receive data from an Apache Artemis message broker by using\
          \ JMS."
        required:
        - "destinationName"
        - "brokerURL"
        type: "object"
        properties:
          destinationType:
            title: "Destination Type"
            description: "The JMS destination type (queue or topic)."
            type: "string"
            default: "queue"
          destinationName:
            title: "Destination Name"
            description: "The JMS destination name."
            type: "string"
          brokerURL:
            title: "Broker URL"
            description: "The JMS URL."
            type: "string"
            example: "tcp://my-host:61616"
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-kafka-sink"
    spec:
      definition:
        title: "Managed Kafka Sink"
        description: |-
          Send data to Managed Kafka topics.

          Optionally, you can set the following properties in the header:

          - `key`: as message key

          - `partition-key`: as message partition key
        required:
        - "topic"
        - "bootstrapServers"
        type: "object"
        properties:
          topic:
            title: "Topic Name"
            description: "The name of the Kafka Topic to use."
            type: "string"
          bootstrapServers:
            title: "Bootstrap Servers"
            description: "Comma separated list of Kafka Broker URLs"
            type: "string"
          securityProtocol:
            title: "Security Protocol"
            description: "Protocol used to communicate with brokers. SASL_PLAINTEXT,\
              \ PLAINTEXT, SASL_SSL and SSL are supported"
            type: "string"
          saslMechanism:
            title: "SASL Mechanism"
            description: "The Simple Authentication and Security Layer (SASL) Mechanism\
              \ used."
            type: "string"
          user:
            title: "Username"
            description: "Username to authenticate to Kafka"
            type: "string"
            x-descriptors:
            - "urn:camel:group:credentials"
          password:
            title: "Password"
            description: "Password to authenticate to kafka"
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
