apiVersion: "sco1237896.github.com/v1"
kind: "ConnectorDefinition"
metadata:
  name: "jira_add_issue_sink_v1"
spec:
  definition:
    apiVersion: "camel.apache.org/v1"
    kind: "Pipe"
    metadata:
      annotations:
        sco1237896.github.com/catalog.group: "saas"
        sco1237896.github.com/catalog.id: "jira"
        sco1237896.github.com/connector.description: "Add a new issue to Jira."
        sco1237896.github.com/connector.group: "saas"
        sco1237896.github.com/connector.id: "jira_add_issue_sink_v1"
        sco1237896.github.com/connector.title: "Jira Add Issue sink"
        sco1237896.github.com/connector.version: "v1"
        trait.camel.apache.org/container.request-cpu: "0.20"
        trait.camel.apache.org/container.request-memory: "128M"
        trait.camel.apache.org/deployment.progress-deadline-seconds: "30"
        trait.camel.apache.org/container.image: "quay.io/sco1237896/connector-jira:main-b0bc19971c883b500f8fbf96545c4dbefdaf8e9a"
    spec:
      errorHandler:
        log: {}
      sink:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-jira-add-issue-sink"
      source:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-kafka-source"
  resources:
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-kafka-source"
    spec:
      definition:
        title: "Managed Kafka Source"
        description: "Receive data from Managed Kafka topics."
        required:
        - "topic"
        - "bootstrapServers"
        type: "object"
        properties:
          topic:
            title: "Topic Names"
            description: "A comma-separated list of Kafka topic names."
            type: "string"
          bootstrapServers:
            title: "Bootstrap Servers"
            description: "Comma separated list of Kafka Broker URLs"
            type: "string"
          securityProtocol:
            title: "Security Protocol"
            description: "Protocol used to communicate with brokers. SASL_PLAINTEXT,\
              \ PLAINTEXT, SASL_SSL and SSL are supported"
            type: "string"
          saslMechanism:
            title: "SASL Mechanism"
            description: "The Simple Authentication and Security Layer (SASL) Mechanism\
              \ used."
            type: "string"
          user:
            title: "Username"
            description: "Username to authenticate to Kafka"
            type: "string"
            x-descriptors:
            - "urn:camel:group:credentials"
          password:
            title: "Password"
            description: "Password to authenticate to kafka"
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-jira-add-issue-sink"
    spec:
      definition:
        title: "Jira Add Issue Sink"
        description: |-
          Add a new issue to Jira.

          The Kamelet expects the following headers to be set:

          - `projectKey` / `ce-projectKey`: as the Jira project key.

          - `issueTypeName` / `ce-issueTypeName`: as the name of the issue type (example: Bug, Enhancement).

          - `issueSummary` / `ce-issueSummary`: as the title or summary of the issue.

          - `issueAssignee` / `ce-issueAssignee`: as the user assigned to the issue (Optional).

          - `issuePriorityName` / `ce-issuePriorityName`: as the priority name of the issue (example: Critical, Blocker, Trivial) (Optional).

          - `issueComponents` / `ce-issueComponents`: as list of string with the valid component names (Optional).

          - `issueDescription` / `ce-issueDescription`: as the issue description (Optional).

          The issue description can be set from the body of the message or the `issueDescription`/`ce-issueDescription` in the header, however the body takes precedence.
        required:
        - "jiraUrl"
        - "username"
        - "password"
        type: "object"
        properties:
          jiraUrl:
            title: "Jira URL"
            description: "The URL of your instance of Jira"
            type: "string"
            example: "http://my_jira.com:8081"
          username:
            title: "Username"
            description: "The username to access Jira"
            type: "string"
            x-descriptors:
            - "urn:camel:group:credentials"
          password:
            title: "Password"
            description: "The password or the API Token to access Jira"
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
      types:
        in:
          mediaType: "application/json"
