apiVersion: "sco1237896.github.com/v1"
kind: "ConnectorDefinition"
metadata:
  name: "salesforce_delete_sink_v1"
spec:
  definition:
    apiVersion: "camel.apache.org/v1"
    kind: "Pipe"
    metadata:
      annotations:
        sco1237896.github.com/catalog.group: "saas"
        sco1237896.github.com/catalog.id: "salesforce"
        sco1237896.github.com/connector.description: "Delete an object in Salesforce."
        sco1237896.github.com/connector.group: "saas"
        sco1237896.github.com/connector.id: "salesforce_delete_sink_v1"
        sco1237896.github.com/connector.title: "Salesforce Delete sink"
        sco1237896.github.com/connector.version: "v1"
        trait.camel.apache.org/container.request-cpu: "0.20"
        trait.camel.apache.org/container.request-memory: "128M"
        trait.camel.apache.org/deployment.progress-deadline-seconds: "30"
        trait.camel.apache.org/container.image: "quay.io/sco1237896/connector-salesforce:main-b0bc19971c883b500f8fbf96545c4dbefdaf8e9a"
    spec:
      errorHandler:
        log: {}
      sink:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-salesforce-delete-sink"
      source:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-kafka-source"
  resources:
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-kafka-source"
    spec:
      definition:
        title: "Managed Kafka Source"
        description: "Receive data from Managed Kafka topics."
        required:
        - "topic"
        - "bootstrapServers"
        type: "object"
        properties:
          topic:
            title: "Topic Names"
            description: "A comma-separated list of Kafka topic names."
            type: "string"
          bootstrapServers:
            title: "Bootstrap Servers"
            description: "Comma separated list of Kafka Broker URLs"
            type: "string"
          securityProtocol:
            title: "Security Protocol"
            description: "Protocol used to communicate with brokers. SASL_PLAINTEXT,\
              \ PLAINTEXT, SASL_SSL and SSL are supported"
            type: "string"
          saslMechanism:
            title: "SASL Mechanism"
            description: "The Simple Authentication and Security Layer (SASL) Mechanism\
              \ used."
            type: "string"
          user:
            title: "Username"
            description: "Username to authenticate to Kafka"
            type: "string"
            x-descriptors:
            - "urn:camel:group:credentials"
          password:
            title: "Password"
            description: "Password to authenticate to kafka"
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-salesforce-delete-sink"
    spec:
      definition:
        title: "Salesforce Delete Sink"
        description: "Remove an object from Salesforce. \n\nThe data body must be\
          \ JSON-formatted and it must\ncontain two keys: `sObjectId` and `sObjectName`.\
          \ For example: `{ \"sObjectId\": \"XXXXX0\", \"sObjectName\": \"Contact\"\
          \ }`"
        required:
        - "clientId"
        - "clientSecret"
        - "userName"
        - "password"
        type: "object"
        properties:
          loginUrl:
            title: "Login URL"
            description: "The Salesforce instance login URL."
            type: "string"
            default: "https://login.salesforce.com"
          clientId:
            title: "Consumer Key"
            description: "The Salesforce application consumer key."
            type: "string"
            x-descriptors:
            - "urn:camel:group:credentials"
          clientSecret:
            title: "Consumer Secret"
            description: "The Salesforce application consumer secret."
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
          userName:
            title: "Username"
            description: "The Salesforce username."
            type: "string"
            x-descriptors:
            - "urn:camel:group:credentials"
          password:
            title: "Password"
            description: "The Salesforce user password."
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
      types:
        in:
          mediaType: "application/json"
          schema:
            type: "object"
            required:
            - "sObjectId"
            - "sObjectName"
            properties:
              sObjectId:
                type: "string"
              sObjectName:
                type: "string"
