apiVersion: "sco1237896.github.com/v1"
kind: "ConnectorDefinition"
metadata:
  name: "salesforce_create_sink_v1"
spec:
  definition:
    apiVersion: "camel.apache.org/v1"
    kind: "Pipe"
    metadata:
      annotations:
        sco1237896.github.com/catalog.group: "saas"
        sco1237896.github.com/catalog.id: "salesforce"
        sco1237896.github.com/connector.description: "Create an object in Salesforce."
        sco1237896.github.com/connector.group: "saas"
        sco1237896.github.com/connector.id: "salesforce_create_sink_v1"
        sco1237896.github.com/connector.title: "Salesforce Create sink"
        sco1237896.github.com/connector.version: "v1"
        trait.camel.apache.org/container.request-cpu: "0.20"
        trait.camel.apache.org/container.request-memory: "128M"
        trait.camel.apache.org/deployment.progress-deadline-seconds: "30"
        trait.camel.apache.org/container.image: "quay.io/sco1237896/connector-salesforce:main-17140b59c01c7dd0a2d657dfcbf5c346ff4a6705"
    spec:
      errorHandler:
        log: {}
      sink:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-salesforce-create-sink"
      source:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-kafka-source"
  resources:
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-kafka-source"
    spec:
      definition:
        title: "Managed Kafka Source"
        description: "Receive data from Managed Kafka topics."
        required:
        - "topic"
        - "bootstrapServers"
        type: "object"
        properties:
          topic:
            title: "Topic Names"
            description: "A comma-separated list of Kafka topic names."
            type: "string"
          bootstrapServers:
            title: "Bootstrap Servers"
            description: "Comma separated list of Kafka Broker URLs"
            type: "string"
          securityProtocol:
            title: "Security Protocol"
            description: "Protocol used to communicate with brokers. SASL_PLAINTEXT,\
              \ PLAINTEXT, SASL_SSL and SSL are supported"
            type: "string"
          saslMechanism:
            title: "SASL Mechanism"
            description: "The Simple Authentication and Security Layer (SASL) Mechanism\
              \ used."
            type: "string"
          user:
            title: "Username"
            description: "Username to authenticate to Kafka"
            type: "string"
            x-descriptors:
            - "urn:camel:group:credentials"
          password:
            title: "Password"
            description: "Password to authenticate to kafka"
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-salesforce-create-sink"
    spec:
      definition:
        title: "Salesforce Create Sink"
        description: "Create an object in Salesforce. \n\nThe body of the message\
          \ must contain the JSON of the Salesforce object, for example: `{ \"Phone\"\
          : \"555\", \"Name\": \"Antonia\", \"LastName\": \"Garcia\" }`."
        required:
        - "clientId"
        - "clientSecret"
        - "userName"
        - "password"
        type: "object"
        properties:
          sObjectName:
            title: "Object Name"
            description: "The type of the object."
            type: "string"
            example: "Contact"
          loginUrl:
            title: "Login URL"
            description: "The Salesforce instance login URL."
            type: "string"
            default: "https://login.salesforce.com"
          clientId:
            title: "Consumer Key"
            description: "The Salesforce application consumer key."
            type: "string"
            x-descriptors:
            - "urn:camel:group:credentials"
          clientSecret:
            title: "Consumer Secret"
            description: "The Salesforce application consumer secret."
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
          userName:
            title: "Username"
            description: "The Salesforce username."
            type: "string"
            x-descriptors:
            - "urn:camel:group:credentials"
          password:
            title: "Password"
            description: "The Salesforce user password."
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
      types:
        in:
          mediaType: "application/json"
