apiVersion: "sco1237896.github.com/v1"
kind: "ConnectorDefinition"
metadata:
  name: "postgresql_sink_v1"
spec:
  definition:
    apiVersion: "camel.apache.org/v1"
    kind: "Pipe"
    metadata:
      annotations:
        sco1237896.github.com/catalog.group: "sql"
        sco1237896.github.com/catalog.id: "postgresql"
        sco1237896.github.com/connector.description: "Send data to a PostgreSQL Database."
        sco1237896.github.com/connector.group: "sql"
        sco1237896.github.com/connector.id: "postgresql_sink_v1"
        sco1237896.github.com/connector.title: "PostgreSQL sink"
        sco1237896.github.com/connector.version: "v1"
        trait.camel.apache.org/container.request-cpu: "0.20"
        trait.camel.apache.org/container.request-memory: "128M"
        trait.camel.apache.org/deployment.progress-deadline-seconds: "30"
        trait.camel.apache.org/container.image: "quay.io/sco1237896/connector-postgresql:main-b0bc19971c883b500f8fbf96545c4dbefdaf8e9a"
    spec:
      errorHandler:
        log: {}
      sink:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-postgresql-sink"
      source:
        ref:
          apiVersion: "camel.apache.org/v1"
          kind: "Kamelet"
          name: "connector-kafka-source"
  resources:
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-kafka-source"
    spec:
      definition:
        title: "Managed Kafka Source"
        description: "Receive data from Managed Kafka topics."
        required:
        - "topic"
        - "bootstrapServers"
        type: "object"
        properties:
          topic:
            title: "Topic Names"
            description: "A comma-separated list of Kafka topic names."
            type: "string"
          bootstrapServers:
            title: "Bootstrap Servers"
            description: "Comma separated list of Kafka Broker URLs"
            type: "string"
          securityProtocol:
            title: "Security Protocol"
            description: "Protocol used to communicate with brokers. SASL_PLAINTEXT,\
              \ PLAINTEXT, SASL_SSL and SSL are supported"
            type: "string"
          saslMechanism:
            title: "SASL Mechanism"
            description: "The Simple Authentication and Security Layer (SASL) Mechanism\
              \ used."
            type: "string"
          user:
            title: "Username"
            description: "Username to authenticate to Kafka"
            type: "string"
            x-descriptors:
            - "urn:camel:group:credentials"
          password:
            title: "Password"
            description: "Password to authenticate to kafka"
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
  - apiVersion: "camel.apache.org/v1alpha1"
    kind: "Kamelet"
    metadata:
      name: "connector-postgresql-sink"
    spec:
      definition:
        title: "PostgreSQL Sink"
        description: |-
          Send data to a PostgreSQL Database.

          This Kamelet expects a JSON-formatted body. Use key:value pairs to map the JSON fields and parameters. For example, here is a query:

          'INSERT INTO accounts (username,city) VALUES (:#username,:#city)'

          Here is example input for the example query:

          '{ "username":"oscerd", "city":"Rome"}'
        required:
        - "serverName"
        - "username"
        - "password"
        - "query"
        - "databaseName"
        type: "object"
        properties:
          serverName:
            title: "Server Name"
            description: "The server name for the data source."
            type: "string"
            example: "localhost"
          serverPort:
            title: "Server Port"
            description: "The server port for the data source."
            type: "string"
            default: 5432
          username:
            title: "Username"
            description: "The username to access a secured PostgreSQL Database."
            type: "string"
            x-descriptors:
            - "urn:camel:group:credentials"
          password:
            title: "Password"
            description: "The password to access a secured PostgreSQL Database."
            type: "string"
            format: "password"
            x-descriptors:
            - "urn:alm:descriptor:com.tectonic.ui:password"
            - "urn:camel:group:credentials"
          query:
            title: "Query"
            description: "The query to execute against the PostgreSQL Database."
            type: "string"
            example: "INSERT INTO accounts (username,city) VALUES (:#username,:#city)"
          databaseName:
            title: "Database Name"
            description: "The name of the PostgreSQL Database."
            type: "string"
      types:
        in:
          mediaType: "application/json"
