name: Build Catalog

on:
  push:
    branches:
      - main
    paths:
      - "connectors/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref_name}}-${{ github.workflow }}
  cancel-in-progress: true

env:
  LANG: en_US.UTF-8
  CONNECTORS_DIR: connectors
  PROJECTS: ${{ github.workspace }}

jobs:
  image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        overlay:
          - "dev"
    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Set versions
        run: |
          export C_VERSION="${GITHUB_REF_NAME#v}" 
          export C_REVISION="${GITHUB_SHA}" 

          echo "CONNECTORS_VERSION=${C_VERSION}" >> $GITHUB_ENV
          echo "CONNECTORS_REVISION=${C_REVISION}" >> $GITHUB_ENV
          echo "CONNECTORS_RELEASE=${C_VERSION}-${C_REVISION}" >> $GITHUB_ENV

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build Catalog Image
        run: |
          docker build \
            -t "quay.io/sco1237896/connectors-catalog:${CONNECTORS_RELEASE}" \
            -t "quay.io/sco1237896/connectors-catalog:latest" \
            -f etc/Dockerfile.catalog ./connectors

          docker push "quay.io/sco1237896/connectors-catalog:${CONNECTORS_RELEASE}"
          docker push "quay.io/sco1237896/connectors-catalog:latest"
